from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class SourceType(str, Enum):
    url = "url"
    description = "description"
    none = "none"


class ProductInput(BaseModel):
    """Stage 1 — what the user submits via the form."""

    product_name: str = Field(..., min_length=1)
    target_audience: str = Field(..., min_length=1)
    source_type: SourceType
    source_url: Optional[str] = None
    source_description: Optional[str] = None

    # Manual fallback fields, required only when source_type == none
    manual_ingredients: Optional[str] = None
    manual_usp: Optional[str] = None


class StructuredProduct(BaseModel):
    """Stage 3 output — what every later stage consumes."""

    product_name: str
    target_audience: str
    ingredients: list[str] = Field(default_factory=list)
    usp: str = ""
    tone: str = ""
    key_benefits: list[str] = Field(default_factory=list)
    industry: str = ""
    pain_points: list[str] = Field(default_factory=list)
    marketing_angle: str = ""
    key_emotions: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)
    missing_fields: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)


class StorySituation(BaseModel):
    """Stage 3.5 output item — a creative marketing angle, not a script.

    Represents a person, problem, context, or emotional journey that could
    become a script. Generated by an AI creative director from the structured
    product profile; the user picks one before Stage 6 writes an actual script.
    """

    id: str
    title: str
    description: str
    emotion: str
    persona: str
    marketing_angle: str
    category: str  # e.g. "Emotional", "Educational" — Claude-generated, not an enum
    difficulty: str  # "easy" | "medium" | "hard" — production complexity
    estimated_length: str  # e.g. "15s" | "30s" | "60s"
    virality_score: float = Field(ge=0.0, le=10.0)


class StorySituationsInput(BaseModel):
    """Stage 3.5 input — ask Claude for N diverse story situations for a product."""

    structured_product: StructuredProduct
    product_category: str = Field(..., min_length=1)
    count: int = 10
    exclude_titles: list[str] = Field(default_factory=list)


class StorySituationsResult(BaseModel):
    situations: list[StorySituation] = Field(default_factory=list)


class ScriptGenerationInput(BaseModel):
    """Stage 6 input — structured product data plus the chosen story situation.

    similar_past_winners is optional and stays empty until Stage 5 (retrieval)
    is wired up — Stage 6 works without it, just with less grounding.
    """

    structured_product: StructuredProduct
    selected_situation: StorySituation
    product_category: str = Field(..., min_length=1)
    platform: str = "instagram_reel"
    similar_past_winners: list[str] = Field(default_factory=list)
    max_line_chars: int = 90


class ScriptLine(BaseModel):
    text: str
    visual_tags: list[str] = Field(default_factory=list)
    scene_label: Optional[str] = None
    visual_direction: Optional[str] = None
    camera_angle: Optional[str] = None
    emotion: Optional[str] = None
    lighting: Optional[str] = None
    transition_note: Optional[str] = None


class GeneratedScript(BaseModel):
    """Stage 6 output — consumed directly by Stage 7 (compliance) and Stage 8 (assets)."""

    hook: ScriptLine
    body: list[ScriptLine] = Field(default_factory=list)
    cta: ScriptLine
    situation: Optional[StorySituation] = None
    bgm_suggestion: str = ""

    @property
    def full_text(self) -> str:
        lines = [self.hook.text, *[line.text for line in self.body], self.cta.text]
        return "\n".join(lines)


class AssetSourcingInput(BaseModel):
    """Stage 8 input — one entry per script line, each with its own visual tags."""

    line_id: str = Field(..., description="e.g. 'hook', 'body_0', 'cta' — ties the asset back to a script line")
    visual_tags: list[str] = Field(..., min_length=1)


class AssetCandidate(BaseModel):
    source: str  # "pexels" | "pixabay"
    url: str
    thumbnail_url: str
    width: int
    height: int


class SelectedAsset(BaseModel):
    line_id: str
    tag_used: str
    broadened: bool = False
    candidate: Optional[AssetCandidate] = None
    reasoning: str = ""


class MotionGenerationInput(BaseModel):
    """Stage 8.5 (optional) — animate one sourced image into a short video clip."""

    line_id: str
    image_url: str = Field(..., min_length=1)
    visual_tags: list[str] = Field(default_factory=list)


class MotionGenerationResult(BaseModel):
    line_id: str
    video_path: str
    prompt_used: str


class VoiceoverLine(BaseModel):
    line_id: str
    text: str


class VoiceoverInput(BaseModel):
    lines: list[VoiceoverLine] = Field(..., min_length=1)


class VoiceoverResult(BaseModel):
    line_id: str
    hindi_text: str
    audio_path: str
    duration_seconds: float


class RenderLine(BaseModel):
    text: str
    image_url: str
    video_url: Optional[str] = None
    audio_url: Optional[str] = None
    min_duration_seconds: Optional[float] = None


class RenderInput(BaseModel):
    """Stage 9 input — script lines already paired with their chosen assets."""

    product_name: str = Field(..., min_length=1)
    lines: list[RenderLine] = Field(..., min_length=1)
    seconds_per_line: float = 3.0


class RenderResult(BaseModel):
    output_path: str
    duration_seconds: float


class ComplianceCheckInput(BaseModel):
    """Stage 7 input — the final script text plus category context.

    Independent from whatever produced the script (Stage 6 today, anything
    else later) — this stage only ever sees the finished text.
    """

    script_text: str = Field(..., min_length=1)
    product_category: str = Field(..., min_length=1)
    product_name: str = Field(..., min_length=1)


class ComplianceViolation(BaseModel):
    phrase: str
    reason: str
    severity: str  # "blocker" | "warning"


class ComplianceResult(BaseModel):
    """Stage 7 output — pass/fail gate before a script can reach rendering."""

    passed: bool
    violations: list[ComplianceViolation] = Field(default_factory=list)
    notes: str = ""


class RewriteDirective(str, Enum):
    """A single AI quick-action a user can apply to one script line's text."""

    improve = "improve"
    make_viral = "make_viral"
    make_emotional = "make_emotional"
    increase_conversion = "increase_conversion"
    rewrite = "rewrite"


class RewriteLineInput(BaseModel):
    text: str = Field(..., min_length=1)
    directive: RewriteDirective
    max_chars: Optional[int] = None


class RewriteLineResult(BaseModel):
    text: str
