from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class SourceType(str, Enum):
    url = "url"
    description = "description"
    none = "none"


class ScriptLanguage(str, Enum):
    english = "english"
    hindi = "hindi"
    hinglish = "hinglish"


class ScriptSection(str, Enum):
    """Which beat of the 9-part ad structure a script line belongs to."""

    hook = "hook"
    problem = "problem"
    science = "science"
    story = "story"
    product_intro = "product_intro"
    ingredients = "ingredients"
    benefits = "benefits"
    objection_handling = "objection_handling"
    cta = "cta"


class ScriptRegenerateScope(str, Enum):
    """Which part of an already-generated script a regeneration request targets."""

    full = "full"
    hook = "hook"
    cta = "cta"
    science = "science"
    story = "story"
    product_explanation = "product_explanation"
    emotional_tone = "emotional_tone"
    length = "length"


class ReferenceKind(str, Enum):
    """What a reference material is, for card icon/label + extraction dispatch."""

    pdf = "pdf"
    docx = "docx"
    pptx = "pptx"
    doc = "doc"
    ppt = "ppt"
    txt = "txt"
    csv = "csv"
    xlsx = "xlsx"
    zip = "zip"
    image = "image"
    video = "video"
    audio = "audio"
    website = "website"
    google_drive = "google_drive"
    youtube = "youtube"
    dropbox = "dropbox"
    notion = "notion"


class ReferenceAnalysis(str, Enum):
    """Whether a reference material's content actually made it into the AI's context."""

    analyzed = "analyzed"
    coming_soon = "coming_soon"  # video/audio — stored + previewable, not analyzed yet
    not_supported = "not_supported"  # legacy .doc/.ppt — no extractor available
    failed = "failed"


class ReferenceMaterial(BaseModel):
    """One uploaded file or pasted link attached as supporting context for Stage 3."""

    id: str
    kind: ReferenceKind
    filename: Optional[str] = None
    source_url: Optional[str] = None
    stored_path: Optional[str] = None
    mime_type: Optional[str] = None
    size_bytes: Optional[int] = None
    analysis: ReferenceAnalysis
    extracted_text: str = ""
    truncated: bool = False
    note: str = ""


class FetchUrlInput(BaseModel):
    url: str = Field(..., min_length=1)


class FetchUrlResult(BaseModel):
    raw_text: str
    title: str = ""
    char_count: int = 0
    truncated: bool = False


class AutoFillInput(BaseModel):
    raw_text: str = Field(..., min_length=1)
    source_url: Optional[str] = None


class AutoFillSuggestion(BaseModel):
    """A first-draft, editable product profile guessed from raw scraped/extracted text."""

    product_name: str = ""
    target_audience: str = ""
    source_description: str = ""
    product_category: str = ""
    brand: str = ""
    keywords: list[str] = Field(default_factory=list)
    key_benefits: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)


class ProductInput(BaseModel):
    """Stage 1 — what the user submits via the form."""

    product_name: str = Field(..., min_length=1)
    target_audience: str = Field(..., min_length=1)
    source_type: SourceType
    source_url: Optional[str] = None
    source_description: Optional[str] = None

    # Manual fallback fields, required only when source_type == none
    manual_ingredients: Optional[str] = None
    manual_usp: Optional[str] = None

    # Reference Materials (Step 1 upgrade) — client-cached URL fetch avoids
    # re-hitting Jina Reader at submit time, plus any attached reference files/links.
    source_url_raw_text: Optional[str] = None
    reference_materials: list[ReferenceMaterial] = Field(default_factory=list)


class StructuredProduct(BaseModel):
    """Stage 3 output — what every later stage consumes."""

    product_name: str
    target_audience: str
    ingredients: list[str] = Field(default_factory=list)
    usp: str = ""
    tone: str = ""
    key_benefits: list[str] = Field(default_factory=list)
    industry: str = ""
    pain_points: list[str] = Field(default_factory=list)
    marketing_angle: str = ""
    key_emotions: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)
    missing_fields: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)


class StorySituation(BaseModel):
    """Stage 3.5 output item — a creative marketing angle, not a script.

    Represents a person, problem, context, or emotional journey that could
    become a script. Generated by an AI creative director from the structured
    product profile; the user picks one before Stage 6 writes an actual script.
    """

    id: str
    title: str
    description: str
    emotion: str
    persona: str
    marketing_angle: str
    category: str  # e.g. "Emotional", "Educational" — Gemini-generated, not an enum
    difficulty: str  # "easy" | "medium" | "hard" — production complexity
    estimated_length: str  # e.g. "15s" | "30s" | "60s"
    virality_score: float = Field(ge=0.0, le=10.0)
    # Creative Angle (execution style) — the HOW, distinct from marketing_angle
    # (the WHY/strategy). Labels drawn from creative_angles.CREATIVE_ANGLES.
    recommended_angles: list[str] = Field(default_factory=list)


class StorySituationsInput(BaseModel):
    """Stage 3.5 input — ask Gemini for N diverse story situations for a product."""

    structured_product: StructuredProduct
    product_category: str = Field(..., min_length=1)
    count: int = 10
    exclude_titles: list[str] = Field(default_factory=list)


class StorySituationsResult(BaseModel):
    situations: list[StorySituation] = Field(default_factory=list)


class ScriptGenerationInput(BaseModel):
    """Stage 6 input — structured product data plus the chosen story situation.

    similar_past_winners is optional and stays empty until Stage 5 (retrieval)
    is wired up — Stage 6 works without it, just with less grounding.
    """

    structured_product: StructuredProduct
    selected_situation: StorySituation
    product_category: str = Field(..., min_length=1)
    platform: str = "instagram_reel"
    similar_past_winners: list[str] = Field(default_factory=list)
    max_line_chars: int = 90
    # Creative Angle (execution style) — a catalog label (e.g. "Meta Glasses
    # POV") or arbitrary custom instruction (e.g. "generate like a Netflix
    # documentary"). Empty = no specific execution style requested.
    creative_angle: str = Field("", max_length=300)
    # Spoken/on-screen script language — visual_tags always stay in English
    # (stock-footage search) regardless of this.
    script_language: ScriptLanguage = ScriptLanguage.english
    # Target video duration bucket (e.g. "30s", "60s"). Empty = derive from
    # selected_situation.estimated_length.
    target_duration: str = ""


class ScriptLine(BaseModel):
    text: str
    on_screen_text: str = ""
    visual_tags: list[str] = Field(default_factory=list)
    scene_label: Optional[str] = None
    section: Optional[ScriptSection] = None
    visual_direction: Optional[str] = None
    camera_angle: Optional[str] = None
    emotion: Optional[str] = None
    lighting: Optional[str] = None
    transition_note: Optional[str] = None
    duration_seconds: Optional[float] = None
    b_roll: list[str] = Field(default_factory=list)
    sfx: Optional[str] = None
    ai_image_prompt: str = ""
    ai_video_prompt: str = ""

    @field_validator("section", mode="before")
    @classmethod
    def _blank_section_to_none(cls, v: object) -> object:
        """Gemini occasionally emits "" instead of omitting the field — treat
        that the same as not tagging a section rather than a validation error."""
        return v or None


class GeneratedScript(BaseModel):
    """Stage 6 output — consumed directly by Stage 7 (compliance) and Stage 8 (assets)."""

    hook: ScriptLine
    body: list[ScriptLine] = Field(default_factory=list)
    cta: ScriptLine
    situation: Optional[StorySituation] = None
    bgm_suggestion: str = ""
    creative_angle: str = ""
    script_language: ScriptLanguage = ScriptLanguage.english
    target_duration: str = ""
    estimated_duration_seconds: float = 0.0

    @property
    def full_text(self) -> str:
        lines = [self.hook.text, *[line.text for line in self.body], self.cta.text]
        return "\n".join(lines)


class ScriptSectionRegenerateInput(BaseModel):
    """Targeted regeneration — take an already-generated script and rewrite
    only the requested part, leaving everything else untouched."""

    structured_product: StructuredProduct
    selected_situation: StorySituation
    product_category: str = Field(..., min_length=1)
    platform: str = "instagram_reel"
    max_line_chars: int = 90
    creative_angle: str = Field("", max_length=300)
    script_language: ScriptLanguage = ScriptLanguage.english
    target_duration: str = ""
    current_script: GeneratedScript
    scope: ScriptRegenerateScope = ScriptRegenerateScope.full
    # Free text appended to the scope's guidance — powers one-click actions like
    # "Add More Science" or "Remove Repetition" without needing a new enum value.
    custom_instruction: str = ""
    # Precise numeric word-count target — used by Shorten/Extend/slider controls
    # to override the bucket's normal range with an exact goal.
    target_word_count: Optional[int] = None


class AssetSourcingInput(BaseModel):
    """Stage 8 input — one entry per script line, each with its own visual tags."""

    line_id: str = Field(..., description="e.g. 'hook', 'body_0', 'cta' — ties the asset back to a script line")
    visual_tags: list[str] = Field(..., min_length=1)


class AssetCandidate(BaseModel):
    source: str  # "pexels" | "pixabay"
    url: str
    thumbnail_url: str
    width: int
    height: int


class SelectedAsset(BaseModel):
    line_id: str
    tag_used: str
    broadened: bool = False
    candidate: Optional[AssetCandidate] = None
    reasoning: str = ""


class MotionGenerationInput(BaseModel):
    """Stage 8.5 (optional) — animate one sourced image into a short video clip."""

    line_id: str
    image_url: str = Field(..., min_length=1)
    visual_tags: list[str] = Field(default_factory=list)


class MotionGenerationResult(BaseModel):
    line_id: str
    video_path: str
    prompt_used: str


class VoiceoverLine(BaseModel):
    line_id: str
    text: str


class VoiceoverInput(BaseModel):
    lines: list[VoiceoverLine] = Field(..., min_length=1)


class VoiceoverResult(BaseModel):
    line_id: str
    hindi_text: str
    audio_path: str
    duration_seconds: float


class RenderLine(BaseModel):
    text: str
    image_url: str
    video_url: Optional[str] = None
    audio_url: Optional[str] = None
    min_duration_seconds: Optional[float] = None


class RenderInput(BaseModel):
    """Stage 9 input — script lines already paired with their chosen assets."""

    product_name: str = Field(..., min_length=1)
    lines: list[RenderLine] = Field(..., min_length=1)
    seconds_per_line: float = 3.0


class RenderResult(BaseModel):
    output_path: str
    duration_seconds: float


class ComplianceCheckInput(BaseModel):
    """Stage 7 input — the final script text plus category context.

    Independent from whatever produced the script (Stage 6 today, anything
    else later) — this stage only ever sees the finished text.
    """

    script_text: str = Field(..., min_length=1)
    product_category: str = Field(..., min_length=1)
    product_name: str = Field(..., min_length=1)


class ComplianceViolation(BaseModel):
    phrase: str
    reason: str
    severity: str  # "blocker" | "warning"


class ComplianceResult(BaseModel):
    """Stage 7 output — pass/fail gate before a script can reach rendering."""

    passed: bool
    violations: list[ComplianceViolation] = Field(default_factory=list)
    notes: str = ""


class RewriteDirective(str, Enum):
    """A single AI quick-action a user can apply to one script line's text."""

    improve = "improve"
    make_viral = "make_viral"
    make_emotional = "make_emotional"
    increase_conversion = "increase_conversion"
    rewrite = "rewrite"
    make_shorter = "make_shorter"
    make_longer = "make_longer"
    more_cinematic = "more_cinematic"
    more_conversational = "more_conversational"
    more_scientific = "more_scientific"
    more_persuasive = "more_persuasive"
    simplify = "simplify"
    professional_tone = "professional_tone"
    funny = "funny"
    fear_based = "fear_based"
    doctor_style = "doctor_style"
    storytelling_style = "storytelling_style"
    ugc_style = "ugc_style"
    podcast_style = "podcast_style"
    meta_glasses_pov = "meta_glasses_pov"
    translate = "translate"


class RewriteLineInput(BaseModel):
    text: str = Field(..., min_length=1)
    directive: RewriteDirective
    max_chars: Optional[int] = None
    # Only used when directive == translate.
    target_language: Optional[ScriptLanguage] = None


class RewriteLineResult(BaseModel):
    text: str


class GenerateAlternativesResult(BaseModel):
    alternatives: list[str] = Field(default_factory=list)


class ScriptSuggestion(BaseModel):
    """One AI-generated improvement suggestion for a finished script."""

    line_id: Optional[str] = None
    section: Optional[ScriptSection] = None
    message: str
    action_label: str
    suggested_scope: Optional[ScriptRegenerateScope] = None

    @field_validator("section", "suggested_scope", "line_id", mode="before")
    @classmethod
    def _blank_to_none(cls, v: object) -> object:
        return v or None


class ScriptSuggestionsResult(BaseModel):
    suggestions: list[ScriptSuggestion] = Field(default_factory=list)


class ScriptSuggestionsInput(BaseModel):
    script: GeneratedScript
    target_duration: str = ""


class VisualSceneLabel(str, Enum):
    hook = "hook"
    emotional = "emotional"
    transformation = "transformation"
    product_shot = "product_shot"
    social_proof = "social_proof"
    testimonial = "testimonial"
    ugc = "ugc"
    lifestyle = "lifestyle"


class VisualConceptStyleParams(BaseModel):
    """Fields exposed in the "Edit Prompt" modal — merged into the final
    generation prompt when non-empty."""

    style: str = ""
    lighting: str = ""
    camera: str = ""
    mood: str = ""
    background: str = ""
    characters: str = ""
    composition: str = ""
    brand_colors: str = ""
    logo_placement: str = ""
    product_position: str = ""
    negative_prompt: str = ""


class VisualConceptScores(BaseModel):
    """Gemini Vision's assessment of a rendered concept — an AI judgment call
    against stated creative criteria, not a validated ad-industry metric."""

    visual_impact: int = 0
    ad_quality: int = 0
    ctr_prediction: int = 0
    emotion_score: int = 0
    brand_match: int = 0
    photorealism: int = 0
    notes: str = ""


class VisualConcept(BaseModel):
    id: str
    scene_number: int
    scene_title: str
    scene_label: VisualSceneLabel
    creative_angle: str = ""
    aspect_ratio: str = "9:16"
    prompt: str
    style_params: VisualConceptStyleParams = Field(default_factory=VisualConceptStyleParams)
    image_path: str = ""
    scores: Optional[VisualConceptScores] = None
    favorite: bool = False
    seed: Optional[int] = None
    resolution: str = ""
    generation_time_seconds: float = 0.0
    used_model: str = ""

    @field_validator("scene_label", mode="before")
    @classmethod
    def _blank_scene_label_to_hook(cls, v: object) -> object:
        return v or "hook"


class VisualConceptsInput(BaseModel):
    structured_product: StructuredProduct
    script: GeneratedScript
    situation: StorySituation
    creative_angle: str = ""
    product_category: str = ""


class VisualConceptsResult(BaseModel):
    concepts: list[VisualConcept] = Field(default_factory=list)


class VisualConceptRegenerateInput(BaseModel):
    structured_product: StructuredProduct
    script: GeneratedScript
    situation: StorySituation
    creative_angle: str = ""
    concept: VisualConcept
    variation_style: Optional[str] = None
    as_new_variation: bool = False
    # True when the user edited the prompt/style fields directly (Edit Prompt
    # modal) — routes through image-conditioned editing instead of a fresh
    # from-scratch generation, same as variation_style.
    is_manual_edit: bool = False


class VisualConceptScoreInput(BaseModel):
    concept: VisualConcept


class VisualConceptDownloadInput(BaseModel):
    concept: VisualConcept
    format: str = "png"


class TestImageResult(BaseModel):
    """Diagnostic — isolates whether a failure is in the HF pipeline itself
    vs. the script-to-image flow around it."""

    image_path: str
    used_model: str = ""
    elapsed_seconds: float = 0.0


class VisualConceptDebugInfo(BaseModel):
    """Static config + a live connectivity check — fast, no image generation."""

    api_key_loaded: bool
    model: str
    api_url: str
    internet_access: bool
